name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on cp${{ matrix.python }}-linux

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-2019, macos-11]
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']
        torch: ['1.11', '1.12', '2.0.0']
        cuda: ['10', '11', '12']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.1
        env:
          CIBW_BUILD: cp${{ matrix.python }}-linux
          CIBW_ENVIRONMENT: TORCH_VERSION=${{ matrix.torch }} CUDA_VERSION=${{ matrix.cuda }}
          
        with:
          package-dir: .
          output-dir: wheelhouse

          
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: ./wheelhouse/*.whl
